[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "sh -c 'psql \"$DATABASE_URL\" -c \"CREATE SCHEMA IF NOT EXISTS tenant;\" && npx prisma db push --accept-data-loss && npx prisma migrate deploy && node dist/main.js'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
